name: Week 1 Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      
name: Get repository code
      uses: actions/checkout@v4

      
name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

      
name: Compile project
      run: |
        javac -d out src/com/cheatguard/watchdog/ProcessInfo.java src/com/cheatguard/watchdog/ProcessScanner.java src/com/cheatguard/Main.java

      
name: Run Week 1 scanner
      run: |
        java -cp out com.cheatguard.Main
